const languages = {
  "ko": {
    "title": "주희의 로또 번호 추천기 & 동물상 테스트",
    "lotto_title": "주희의 로또 번호 추천기",
    "lotto_subtitle": "버튼을 누르면 1~45 중 중복 없이 6개씩, 5게임이 한 번에 생성됩니다.",
    "lotto_generate": "🎲 5게임 생성",
    "lotto_copy": "📋 전체 복사",
    "lotto_clear": "🧼 초기화",
    "lotto_guide": "안내",
    "lotto_no_number": "아직 생성된 번호가 없습니다.",
    "lotto_status_wait": "상태: 대기",
    "lotto_status_done": "상태: 생성 완료 ✅",
    "lotto_status_copy_done": "상태: 복사 완료 📋✅",
    "lotto_status_copy_fail": "상태: 복사 실패 ❌",
    "lotto_gen_time": "생성 시간",
    "lotto_game": "번 게임",
    "animal_title": "동물상 테스트",
    "animal_subtitle": "사진 파일을 업로드하면 강아지상/고양이상 중 어떤 느낌인지 판단합니다.",
    "animal_analyze": "🐾 사진 분석",
    "animal_clear": "🧹 사진 제거",
    "animal_upload": "사진 업로드",
    "animal_preview": "사진을 선택하면 미리보기가 표시됩니다.",
    "animal_notice": "※ 얼굴이 잘 보이는 사진일수록 정확도가 좋아요. 카메라 접근은 사용하지 않습니다.",
    "animal_result": "결과",
    "animal_wait": "대기 중",
    "animal_status_wait": "상태: 대기",
    "animal_status_loading": "상태: 모델 로딩 중...",
    "animal_status_analyzing": "상태: 분석 중 ✅",
    "animal_status_done": "상태: 분석 완료 ✅",
    "animal_status_fail": "상태: 분석 실패 ❌",
    "animal_update_time": "업데이트",
    "animal_model": "모델: 강아지상 · 고양이상",
    "theme_dark": "🌙 다크모드",
    "theme_light": "☀️ 화이트모드"
  },
  "en": {
    "title": "Juhee's Lotto Number Recommender & Animal Face Test",
    "lotto_title": "Juhee's Lotto Number Recommender",
    "lotto_subtitle": "Press the button to generate 5 games of 6 unique numbers from 1 to 45.",
    "lotto_generate": "🎲 Generate 5 Games",
    "lotto_copy": "📋 Copy All",
    "lotto_clear": "🧼 Clear",
    "lotto_guide": "Guide",
    "lotto_no_number": "No numbers generated yet.",
    "lotto_status_wait": "Status: Waiting",
    "lotto_status_done": "Status: Generation Complete ✅",
    "lotto_status_copy_done": "Status: Copy Complete 📋✅",
    "lotto_status_copy_fail": "Status: Copy Failed ❌",
    "lotto_gen_time": "Generation Time",
    "lotto_game": "Game",
    "animal_title": "Animal Face Test",
    "animal_subtitle": "Upload a photo to see if you have a dog-like or cat-like face.",
    "animal_analyze": "🐾 Analyze Photo",
    "animal_clear": "🧹 Remove Photo",
    "animal_upload": "Upload Photo",
    "animal_preview": "Select a photo to see a preview.",
    "animal_notice": "※ Photos with a clear view of the face provide better accuracy. Camera access is not used.",
    "animal_result": "Result",
    "animal_wait": "Waiting",
    "animal_status_wait": "Status: Waiting",
    "animal_status_loading": "Status: Loading model...",
    "animal_status_analyzing": "Status: Analyzing ✅",
    "animal_status_done": "Status: Analysis Complete ✅",
    "animal_status_fail": "Status: Analysis Failed ❌",
    "animal_update_time": "Updated",
    "animal_model": "Model: Dog-like · Cat-like",
    "theme_dark": "🌙 Dark Mode",
    "theme_light": "☀️ Light Mode"
  }
}
